server:
  port: 8080

spring:
  application:
    name: bigChatBrasil

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/BCB
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true


api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}